// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package state

import (
	"database/sql"
	"time"
)

type AbuseReport struct {
	ID              string
	PublicationID   string
	Slug            string
	ReporterEmail   sql.NullString
	ReporterIp      string
	Reason          string
	Details         sql.NullString
	Status          string
	Severity        string
	AnalysisSummary sql.NullString
	AutoBlocked     bool
	CreatedAt       time.Time
	ReviewedAt      sql.NullTime
}

type AccessLog struct {
	ID            string
	PublicationID string
	Slug          string
	Path          string
	Ip            string
	UserAgent     string
	UserID        sql.NullString
	Email         sql.NullString
	Allowed       bool
	Status        int32
	CreatedAt     time.Time
}

type Agent struct {
	ID             string
	ExternalIDHash string
	Name           string
	FirstIp        string
	LastIp         string
	StorageBytes   int64
	BlockedAt      sql.NullTime
	BlockedReason  sql.NullString
	CreatedAt      time.Time
	LastSeenAt     time.Time
}

type ApiKey struct {
	ID          string
	UserID      string
	Name        string
	TokenPrefix string
	TokenHash   string
	CreatedAt   time.Time
	ExpiresAt   sql.NullTime
	LastUsedAt  sql.NullTime
}

type Ban struct {
	ID        string
	UserID    sql.NullString
	Email     sql.NullString
	Ip        sql.NullString
	Reason    string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Comment struct {
	ID             string
	PublicationID  string
	ParentID       sql.NullString
	UserID         sql.NullString
	Email          sql.NullString
	Ip             string
	Body           string
	Scope          string
	AnchorText     sql.NullString
	AnchorSelector sql.NullString
	CreatedAt      time.Time
	ArchivedAt     sql.NullTime
	DeletedAt      sql.NullTime
}

type MagicLink struct {
	ID            string
	UserID        string
	Email         string
	TokenHash     string
	Purpose       string
	PublicationID sql.NullString
	ExpiresAt     time.Time
	UsedAt        sql.NullTime
	CreatedAt     time.Time
}

type Publication struct {
	ID                  string
	OwnerID             sql.NullString
	AgentID             sql.NullString
	Mode                string
	CreatedIp           sql.NullString
	Title               string
	Slug                string
	Visibility          string
	RequireRegistration bool
	Files               []string
	SizeBytes           int64
	BlockedAt           sql.NullTime
	BlockedReason       sql.NullString
	ExpiresAt           sql.NullTime
	CreatedAt           time.Time
}

type Session struct {
	ID        string
	UserID    string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Share struct {
	ID            string
	PublicationID string
	Email         string
	UserID        sql.NullString
	TokenHash     sql.NullString
	CreatedAt     time.Time
}

type SignedAccessProof struct {
	ID            string
	PublicationID string
	Email         string
	Ip            string
	UserAgent     string
	TokenID       string
	CreatedAt     time.Time
}

type SignedAccessToken struct {
	ID            string
	PublicationID string
	Email         string
	TokenHash     string
	CreatedAt     time.Time
	ExpiresAt     time.Time
	UsedAt        sql.NullTime
}

type Strike struct {
	ID            string
	UserID        sql.NullString
	Email         sql.NullString
	Ip            sql.NullString
	PublicationID sql.NullString
	AbuseID       sql.NullString
	Reason        string
	Severity      string
	CreatedAt     time.Time
	ExpiresAt     time.Time
}

type User struct {
	ID                   string
	Email                string
	Name                 string
	Provider             string
	PasswordHash         sql.NullString
	AutoProvisioned      bool
	ConfirmationDeadline sql.NullTime
	EmailConfirmedAt     sql.NullTime
	CreatedAt            time.Time
}
