// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package state

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const clearAll = `-- name: ClearAll :exec
TRUNCATE bookmarks, signed_access_proofs, signed_access_tokens, comments, bans, strikes, abuse_reports, access_logs, shares, publications, agents, api_keys, magic_links, sessions, users
`

func (q *Queries) ClearAll(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAll)
	return err
}

const countFastPublicationsByAgentSince = `-- name: CountFastPublicationsByAgentSince :one
SELECT count(*) FROM publications
WHERE mode = 'fast' AND agent_id = $1 AND created_at >= $2
`

type CountFastPublicationsByAgentSinceParams struct {
	AgentID   sql.NullString
	CreatedAt time.Time
}

func (q *Queries) CountFastPublicationsByAgentSince(ctx context.Context, arg CountFastPublicationsByAgentSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFastPublicationsByAgentSince, arg.AgentID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFastPublicationsByIPSince = `-- name: CountFastPublicationsByIPSince :one
SELECT count(*) FROM publications
WHERE mode = 'fast' AND created_ip = $1 AND created_at >= $2
`

type CountFastPublicationsByIPSinceParams struct {
	CreatedIp sql.NullString
	CreatedAt time.Time
}

func (q *Queries) CountFastPublicationsByIPSince(ctx context.Context, arg CountFastPublicationsByIPSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFastPublicationsByIPSince, arg.CreatedIp, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks WHERE user_id = $1 AND publication_id = $2 AND kind = $3
`

type DeleteBookmarkParams struct {
	UserID        string
	PublicationID string
	Kind          string
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, deleteBookmark, arg.UserID, arg.PublicationID, arg.Kind)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, user_id, name, token_prefix, token_hash, created_at, expires_at, last_used_at FROM api_keys WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, tokenHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, tokenHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, provider, password_hash, auto_provisioned, confirmation_deadline, email_confirmed_at, created_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Provider,
		&i.PasswordHash,
		&i.AutoProvisioned,
		&i.ConfirmationDeadline,
		&i.EmailConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, provider, password_hash, auto_provisioned, confirmation_deadline, email_confirmed_at, created_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Provider,
		&i.PasswordHash,
		&i.AutoProvisioned,
		&i.ConfirmationDeadline,
		&i.EmailConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementAgentStorage = `-- name: IncrementAgentStorage :exec
UPDATE agents
SET storage_bytes = storage_bytes + $2,
    last_seen_at = $3
WHERE id = $1
`

type IncrementAgentStorageParams struct {
	ID           string
	StorageBytes int64
	LastSeenAt   time.Time
}

func (q *Queries) IncrementAgentStorage(ctx context.Context, arg IncrementAgentStorageParams) error {
	_, err := q.db.ExecContext(ctx, incrementAgentStorage, arg.ID, arg.StorageBytes, arg.LastSeenAt)
	return err
}

const insertAPIKey = `-- name: InsertAPIKey :exec
INSERT INTO api_keys (id, user_id, name, token_prefix, token_hash, created_at, expires_at, last_used_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAPIKeyParams struct {
	ID          string
	UserID      string
	Name        string
	TokenPrefix string
	TokenHash   string
	CreatedAt   time.Time
	ExpiresAt   sql.NullTime
	LastUsedAt  sql.NullTime
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertAPIKey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenPrefix,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const insertAbuseReport = `-- name: InsertAbuseReport :exec
INSERT INTO abuse_reports (id, publication_id, slug, reporter_email, reporter_ip, reason, details, status, severity, analysis_summary, auto_blocked, created_at, reviewed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertAbuseReportParams struct {
	ID              string
	PublicationID   string
	Slug            string
	ReporterEmail   sql.NullString
	ReporterIp      string
	Reason          string
	Details         sql.NullString
	Status          string
	Severity        string
	AnalysisSummary sql.NullString
	AutoBlocked     bool
	CreatedAt       time.Time
	ReviewedAt      sql.NullTime
}

func (q *Queries) InsertAbuseReport(ctx context.Context, arg InsertAbuseReportParams) error {
	_, err := q.db.ExecContext(ctx, insertAbuseReport,
		arg.ID,
		arg.PublicationID,
		arg.Slug,
		arg.ReporterEmail,
		arg.ReporterIp,
		arg.Reason,
		arg.Details,
		arg.Status,
		arg.Severity,
		arg.AnalysisSummary,
		arg.AutoBlocked,
		arg.CreatedAt,
		arg.ReviewedAt,
	)
	return err
}

const insertAccessLog = `-- name: InsertAccessLog :exec
INSERT INTO access_logs (id, publication_id, slug, path, ip, user_agent, user_id, email, allowed, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertAccessLogParams struct {
	ID            string
	PublicationID string
	Slug          string
	Path          string
	Ip            string
	UserAgent     string
	UserID        sql.NullString
	Email         sql.NullString
	Allowed       bool
	Status        int32
	CreatedAt     time.Time
}

func (q *Queries) InsertAccessLog(ctx context.Context, arg InsertAccessLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAccessLog,
		arg.ID,
		arg.PublicationID,
		arg.Slug,
		arg.Path,
		arg.Ip,
		arg.UserAgent,
		arg.UserID,
		arg.Email,
		arg.Allowed,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const insertBan = `-- name: InsertBan :exec
INSERT INTO bans (id, user_id, email, ip, reason, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertBanParams struct {
	ID        string
	UserID    sql.NullString
	Email     sql.NullString
	Ip        sql.NullString
	Reason    string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertBan(ctx context.Context, arg InsertBanParams) error {
	_, err := q.db.ExecContext(ctx, insertBan,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.Ip,
		arg.Reason,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertComment = `-- name: InsertComment :exec
INSERT INTO comments (id, publication_id, parent_id, user_id, email, ip, body, scope, anchor_text, anchor_selector, created_at, archived_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertCommentParams struct {
	ID             string
	PublicationID  string
	ParentID       sql.NullString
	UserID         sql.NullString
	Email          sql.NullString
	Ip             string
	Body           string
	Scope          string
	AnchorText     sql.NullString
	AnchorSelector sql.NullString
	CreatedAt      time.Time
	ArchivedAt     sql.NullTime
	DeletedAt      sql.NullTime
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) error {
	_, err := q.db.ExecContext(ctx, insertComment,
		arg.ID,
		arg.PublicationID,
		arg.ParentID,
		arg.UserID,
		arg.Email,
		arg.Ip,
		arg.Body,
		arg.Scope,
		arg.AnchorText,
		arg.AnchorSelector,
		arg.CreatedAt,
		arg.ArchivedAt,
		arg.DeletedAt,
	)
	return err
}

const insertMagicLink = `-- name: InsertMagicLink :exec
INSERT INTO magic_links (id, user_id, email, token_hash, purpose, publication_id, expires_at, used_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertMagicLinkParams struct {
	ID            string
	UserID        string
	Email         string
	TokenHash     string
	Purpose       string
	PublicationID sql.NullString
	ExpiresAt     time.Time
	UsedAt        sql.NullTime
	CreatedAt     time.Time
}

func (q *Queries) InsertMagicLink(ctx context.Context, arg InsertMagicLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertMagicLink,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.TokenHash,
		arg.Purpose,
		arg.PublicationID,
		arg.ExpiresAt,
		arg.UsedAt,
		arg.CreatedAt,
	)
	return err
}

const insertPublication = `-- name: InsertPublication :exec
INSERT INTO publications (id, owner_id, agent_id, mode, created_ip, title, slug, visibility, require_registration, files, size_bytes, blocked_at, blocked_reason, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type InsertPublicationParams struct {
	ID                  string
	OwnerID             sql.NullString
	AgentID             sql.NullString
	Mode                string
	CreatedIp           sql.NullString
	Title               string
	Slug                string
	Visibility          string
	RequireRegistration bool
	Files               []string
	SizeBytes           int64
	BlockedAt           sql.NullTime
	BlockedReason       sql.NullString
	ExpiresAt           sql.NullTime
	CreatedAt           time.Time
}

func (q *Queries) InsertPublication(ctx context.Context, arg InsertPublicationParams) error {
	_, err := q.db.ExecContext(ctx, insertPublication,
		arg.ID,
		arg.OwnerID,
		arg.AgentID,
		arg.Mode,
		arg.CreatedIp,
		arg.Title,
		arg.Slug,
		arg.Visibility,
		arg.RequireRegistration,
		pq.Array(arg.Files),
		arg.SizeBytes,
		arg.BlockedAt,
		arg.BlockedReason,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, user_id, expires_at, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertSessionParams struct {
	ID        string
	UserID    string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const insertShare = `-- name: InsertShare :exec
INSERT INTO shares (id, publication_id, email, user_id, token_hash, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertShareParams struct {
	ID            string
	PublicationID string
	Email         string
	UserID        sql.NullString
	TokenHash     sql.NullString
	CreatedAt     time.Time
}

func (q *Queries) InsertShare(ctx context.Context, arg InsertShareParams) error {
	_, err := q.db.ExecContext(ctx, insertShare,
		arg.ID,
		arg.PublicationID,
		arg.Email,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
	)
	return err
}

const insertSignedAccessProof = `-- name: InsertSignedAccessProof :exec
INSERT INTO signed_access_proofs (id, publication_id, email, ip, user_agent, token_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSignedAccessProofParams struct {
	ID            string
	PublicationID string
	Email         string
	Ip            string
	UserAgent     string
	TokenID       string
	CreatedAt     time.Time
}

func (q *Queries) InsertSignedAccessProof(ctx context.Context, arg InsertSignedAccessProofParams) error {
	_, err := q.db.ExecContext(ctx, insertSignedAccessProof,
		arg.ID,
		arg.PublicationID,
		arg.Email,
		arg.Ip,
		arg.UserAgent,
		arg.TokenID,
		arg.CreatedAt,
	)
	return err
}

const insertSignedAccessToken = `-- name: InsertSignedAccessToken :exec
INSERT INTO signed_access_tokens (id, publication_id, email, token_hash, created_at, expires_at, used_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSignedAccessTokenParams struct {
	ID            string
	PublicationID string
	Email         string
	TokenHash     string
	CreatedAt     time.Time
	ExpiresAt     time.Time
	UsedAt        sql.NullTime
}

func (q *Queries) InsertSignedAccessToken(ctx context.Context, arg InsertSignedAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertSignedAccessToken,
		arg.ID,
		arg.PublicationID,
		arg.Email,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.UsedAt,
	)
	return err
}

const insertStrike = `-- name: InsertStrike :exec
INSERT INTO strikes (id, user_id, email, ip, publication_id, abuse_id, reason, severity, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertStrikeParams struct {
	ID            string
	UserID        sql.NullString
	Email         sql.NullString
	Ip            sql.NullString
	PublicationID sql.NullString
	AbuseID       sql.NullString
	Reason        string
	Severity      string
	CreatedAt     time.Time
	ExpiresAt     time.Time
}

func (q *Queries) InsertStrike(ctx context.Context, arg InsertStrikeParams) error {
	_, err := q.db.ExecContext(ctx, insertStrike,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.Ip,
		arg.PublicationID,
		arg.AbuseID,
		arg.Reason,
		arg.Severity,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, email, name, provider, password_hash, auto_provisioned, confirmation_deadline, email_confirmed_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertUserParams struct {
	ID                   string
	Email                string
	Name                 string
	Provider             string
	PasswordHash         sql.NullString
	AutoProvisioned      bool
	ConfirmationDeadline sql.NullTime
	EmailConfirmedAt     sql.NullTime
	CreatedAt            time.Time
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Provider,
		arg.PasswordHash,
		arg.AutoProvisioned,
		arg.ConfirmationDeadline,
		arg.EmailConfirmedAt,
		arg.CreatedAt,
	)
	return err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, user_id, name, token_prefix, token_hash, created_at, expires_at, last_used_at FROM api_keys ORDER BY created_at, id
`

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenPrefix,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAbuseReports = `-- name: ListAbuseReports :many
SELECT id, publication_id, slug, reporter_email, reporter_ip, reason, details, status, severity, analysis_summary, auto_blocked, created_at, reviewed_at FROM abuse_reports ORDER BY created_at, id
`

func (q *Queries) ListAbuseReports(ctx context.Context) ([]AbuseReport, error) {
	rows, err := q.db.QueryContext(ctx, listAbuseReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AbuseReport
	for rows.Next() {
		var i AbuseReport
		if err := rows.Scan(
			&i.ID,
			&i.PublicationID,
			&i.Slug,
			&i.ReporterEmail,
			&i.ReporterIp,
			&i.Reason,
			&i.Details,
			&i.Status,
			&i.Severity,
			&i.AnalysisSummary,
			&i.AutoBlocked,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessLogs = `-- name: ListAccessLogs :many
SELECT id, publication_id, slug, path, ip, user_agent, user_id, email, allowed, status, created_at FROM access_logs ORDER BY created_at, id
`

func (q *Queries) ListAccessLogs(ctx context.Context) ([]AccessLog, error) {
	rows, err := q.db.QueryContext(ctx, listAccessLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessLog
	for rows.Next() {
		var i AccessLog
		if err := rows.Scan(
			&i.ID,
			&i.PublicationID,
			&i.Slug,
			&i.Path,
			&i.Ip,
			&i.UserAgent,
			&i.UserID,
			&i.Email,
			&i.Allowed,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, external_id_hash, name, first_ip, last_ip, storage_bytes, blocked_at, blocked_reason, created_at, last_seen_at FROM agents ORDER BY created_at, id
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.ExternalIDHash,
			&i.Name,
			&i.FirstIp,
			&i.LastIp,
			&i.StorageBytes,
			&i.BlockedAt,
			&i.BlockedReason,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBans = `-- name: ListBans :many
SELECT id, user_id, email, ip, reason, created_at, expires_at FROM bans ORDER BY created_at, id
`

func (q *Queries) ListBans(ctx context.Context) ([]Ban, error) {
	rows, err := q.db.QueryContext(ctx, listBans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ban
	for rows.Next() {
		var i Ban
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Ip,
			&i.Reason,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookmarks = `-- name: ListBookmarks :many
SELECT id, user_id, publication_id, kind, created_at FROM bookmarks ORDER BY created_at, id
`

func (q *Queries) ListBookmarks(ctx context.Context) ([]Bookmark, error) {
	rows, err := q.db.QueryContext(ctx, listBookmarks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bookmark
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PublicationID,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT id, publication_id, parent_id, user_id, email, ip, body, scope, anchor_text, anchor_selector, created_at, archived_at, deleted_at FROM comments ORDER BY created_at, id
`

func (q *Queries) ListComments(ctx context.Context) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listComments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PublicationID,
			&i.ParentID,
			&i.UserID,
			&i.Email,
			&i.Ip,
			&i.Body,
			&i.Scope,
			&i.AnchorText,
			&i.AnchorSelector,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMagicLinks = `-- name: ListMagicLinks :many
SELECT id, user_id, email, token_hash, purpose, publication_id, expires_at, used_at, created_at FROM magic_links ORDER BY created_at, id
`

func (q *Queries) ListMagicLinks(ctx context.Context) ([]MagicLink, error) {
	rows, err := q.db.QueryContext(ctx, listMagicLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MagicLink
	for rows.Next() {
		var i MagicLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.TokenHash,
			&i.Purpose,
			&i.PublicationID,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublications = `-- name: ListPublications :many
SELECT id, owner_id, agent_id, mode, created_ip, title, slug, visibility, require_registration, files, size_bytes, blocked_at, blocked_reason, expires_at, created_at FROM publications ORDER BY created_at, id
`

func (q *Queries) ListPublications(ctx context.Context) ([]Publication, error) {
	rows, err := q.db.QueryContext(ctx, listPublications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Publication
	for rows.Next() {
		var i Publication
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AgentID,
			&i.Mode,
			&i.CreatedIp,
			&i.Title,
			&i.Slug,
			&i.Visibility,
			&i.RequireRegistration,
			pq.Array(&i.Files),
			&i.SizeBytes,
			&i.BlockedAt,
			&i.BlockedReason,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, user_id, expires_at, created_at FROM sessions ORDER BY created_at, id
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShares = `-- name: ListShares :many
SELECT id, publication_id, email, user_id, token_hash, created_at FROM shares ORDER BY created_at, id
`

func (q *Queries) ListShares(ctx context.Context) ([]Share, error) {
	rows, err := q.db.QueryContext(ctx, listShares)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Share
	for rows.Next() {
		var i Share
		if err := rows.Scan(
			&i.ID,
			&i.PublicationID,
			&i.Email,
			&i.UserID,
			&i.TokenHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignedAccessProofs = `-- name: ListSignedAccessProofs :many
SELECT id, publication_id, email, ip, user_agent, token_id, created_at FROM signed_access_proofs ORDER BY created_at, id
`

func (q *Queries) ListSignedAccessProofs(ctx context.Context) ([]SignedAccessProof, error) {
	rows, err := q.db.QueryContext(ctx, listSignedAccessProofs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SignedAccessProof
	for rows.Next() {
		var i SignedAccessProof
		if err := rows.Scan(
			&i.ID,
			&i.PublicationID,
			&i.Email,
			&i.Ip,
			&i.UserAgent,
			&i.TokenID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignedAccessTokens = `-- name: ListSignedAccessTokens :many
SELECT id, publication_id, email, token_hash, created_at, expires_at, used_at FROM signed_access_tokens ORDER BY created_at, id
`

func (q *Queries) ListSignedAccessTokens(ctx context.Context) ([]SignedAccessToken, error) {
	rows, err := q.db.QueryContext(ctx, listSignedAccessTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SignedAccessToken
	for rows.Next() {
		var i SignedAccessToken
		if err := rows.Scan(
			&i.ID,
			&i.PublicationID,
			&i.Email,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrikes = `-- name: ListStrikes :many
SELECT id, user_id, email, ip, publication_id, abuse_id, reason, severity, created_at, expires_at FROM strikes ORDER BY created_at, id
`

func (q *Queries) ListStrikes(ctx context.Context) ([]Strike, error) {
	rows, err := q.db.QueryContext(ctx, listStrikes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Strike
	for rows.Next() {
		var i Strike
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Ip,
			&i.PublicationID,
			&i.AbuseID,
			&i.Reason,
			&i.Severity,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, provider, password_hash, auto_provisioned, confirmation_deadline, email_confirmed_at, created_at FROM users ORDER BY created_at, id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Provider,
			&i.PasswordHash,
			&i.AutoProvisioned,
			&i.ConfirmationDeadline,
			&i.EmailConfirmedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumFastStorageByAgent = `-- name: SumFastStorageByAgent :one
SELECT COALESCE(sum(size_bytes), 0)::bigint FROM publications
WHERE mode = 'fast' AND agent_id = $1 AND (expires_at IS NULL OR expires_at > $2)
`

type SumFastStorageByAgentParams struct {
	AgentID   sql.NullString
	ExpiresAt sql.NullTime
}

func (q *Queries) SumFastStorageByAgent(ctx context.Context, arg SumFastStorageByAgentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumFastStorageByAgent, arg.AgentID, arg.ExpiresAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumFastStorageByIP = `-- name: SumFastStorageByIP :one
SELECT COALESCE(sum(size_bytes), 0)::bigint FROM publications
WHERE mode = 'fast' AND created_ip = $1 AND (expires_at IS NULL OR expires_at > $2)
`

type SumFastStorageByIPParams struct {
	CreatedIp sql.NullString
	ExpiresAt sql.NullTime
}

func (q *Queries) SumFastStorageByIP(ctx context.Context, arg SumFastStorageByIPParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumFastStorageByIP, arg.CreatedIp, arg.ExpiresAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = $2 WHERE id = $1
`

type UpdateAPIKeyLastUsedParams struct {
	ID         string
	LastUsedAt sql.NullTime
}

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, arg.ID, arg.LastUsedAt)
	return err
}

const upsertAgent = `-- name: UpsertAgent :one
INSERT INTO agents (id, external_id_hash, name, first_ip, last_ip, storage_bytes, blocked_at, blocked_reason, created_at, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (external_id_hash) DO UPDATE
SET name = COALESCE(NULLIF(EXCLUDED.name, ''), agents.name),
    last_ip = EXCLUDED.last_ip,
    last_seen_at = EXCLUDED.last_seen_at
RETURNING id, external_id_hash, name, first_ip, last_ip, storage_bytes, blocked_at, blocked_reason, created_at, last_seen_at
`

type UpsertAgentParams struct {
	ID             string
	ExternalIDHash string
	Name           string
	FirstIp        string
	LastIp         string
	StorageBytes   int64
	BlockedAt      sql.NullTime
	BlockedReason  sql.NullString
	CreatedAt      time.Time
	LastSeenAt     time.Time
}

func (q *Queries) UpsertAgent(ctx context.Context, arg UpsertAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, upsertAgent,
		arg.ID,
		arg.ExternalIDHash,
		arg.Name,
		arg.FirstIp,
		arg.LastIp,
		arg.StorageBytes,
		arg.BlockedAt,
		arg.BlockedReason,
		arg.CreatedAt,
		arg.LastSeenAt,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.ExternalIDHash,
		&i.Name,
		&i.FirstIp,
		&i.LastIp,
		&i.StorageBytes,
		&i.BlockedAt,
		&i.BlockedReason,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const upsertBookmark = `-- name: UpsertBookmark :exec
INSERT INTO bookmarks (id, user_id, publication_id, kind, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, publication_id, kind) DO NOTHING
`

type UpsertBookmarkParams struct {
	ID            string
	UserID        string
	PublicationID string
	Kind          string
	CreatedAt     time.Time
}

func (q *Queries) UpsertBookmark(ctx context.Context, arg UpsertBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, upsertBookmark,
		arg.ID,
		arg.UserID,
		arg.PublicationID,
		arg.Kind,
		arg.CreatedAt,
	)
	return err
}
