CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_magic_links_token_hash ON magic_links(token_hash);
CREATE INDEX IF NOT EXISTS idx_magic_links_user_id ON magic_links(user_id);
CREATE INDEX IF NOT EXISTS idx_api_keys_token_hash ON api_keys(token_hash);
CREATE INDEX IF NOT EXISTS idx_api_keys_user_id ON api_keys(user_id);
CREATE INDEX IF NOT EXISTS idx_publications_owner_id ON publications(owner_id);
CREATE INDEX IF NOT EXISTS idx_publications_agent_id ON publications(agent_id);
CREATE INDEX IF NOT EXISTS idx_publications_slug ON publications(slug);
CREATE INDEX IF NOT EXISTS idx_publications_mode_created_ip ON publications(mode, created_ip, created_at);
CREATE INDEX IF NOT EXISTS idx_publications_mode_agent_id ON publications(mode, agent_id, created_at);
CREATE INDEX IF NOT EXISTS idx_publications_expires_at ON publications(expires_at);
CREATE INDEX IF NOT EXISTS idx_shares_publication_id ON shares(publication_id);
CREATE INDEX IF NOT EXISTS idx_shares_email ON shares(email);
CREATE INDEX IF NOT EXISTS idx_access_logs_publication_id ON access_logs(publication_id);
CREATE INDEX IF NOT EXISTS idx_access_logs_created_at ON access_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_abuse_reports_publication_id ON abuse_reports(publication_id);
CREATE INDEX IF NOT EXISTS idx_strikes_expires_at ON strikes(expires_at);
CREATE INDEX IF NOT EXISTS idx_bans_expires_at ON bans(expires_at);
CREATE INDEX IF NOT EXISTS idx_comments_publication_id ON comments(publication_id);
CREATE INDEX IF NOT EXISTS idx_signed_access_tokens_token_hash ON signed_access_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_signed_access_tokens_publication_id ON signed_access_tokens(publication_id);
CREATE INDEX IF NOT EXISTS idx_signed_access_proofs_publication_id ON signed_access_proofs(publication_id);
